name: ifyk_landing
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  auto_route: ^8.1.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.4.1
  scrollable_positioned_list: ^0.3.8
  flutter_riverpod: ^2.5.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  freezed: ^2.4.6
  json_serializable: ^6.7.11
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1


# for updating launcher icons, run 'flutter pub run flutter_launcher_icons'
flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/png/app_icon.png"
    background_color: "#000000"

flutter:

  uses-material-design: true
  assets:
   - assets/png/
   - assets/png/city/
   - assets/jpg/
